### ISSUE TITLE
Comment éditer un poste Uservoice déjà soumis ? Option manquante ?

### ISSUE THREAD

**Issue by LeCampusAzure** [DXFrance/Techdays#1]
Bonjour, j'ai un sujet pour retravailler et il n'est pas clair : comment éditer le post ? Pas possible apparemment pour les contributeurs (même connectés). Merci.

**Comment by pierlag** [comment]
Seul l’admin peut l’editer :
2 solutions : 
-	Tu supprimes et tu fais une nouvelle proposition
-	Tu me donnes le nouveau texte et je m’en occupe 

**Comment by LeCampusAzure** [comment]
Première option, pas bonne : je perds les voix ☺
2ème option : à appliquer. Je te tiens au courant –
Merci,
Marius
